name: finora
services:
  db:
    image: postgres:latest
    container_name: finora_db
    restart: no
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finora_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: finora_adminer
    restart: no
    ports:
      - "8081:8080"

volumes:
  db_data:
  